[Variables]

; Refresh the skin after updating these settings!


PlayerName=CAD
; The interface name for the media player
; http://docs.rainmeter.net/manual-beta/plugins/nowplaying#playerlist

SkinSizeRatio=0.5
SkinWidth=(1000*#SkinSizeRatio#)

ControlColor=255,255,255,255

PrimaryFont=Segoe UI
SecondaryFont=Segoe UI Semilight
FontColor=255,255,255,255

; Padding around the album art
PaddingLeft=(50*#SkinSizeRatio#)
PaddingTop=(300*#SkinSizeRatio#)
PaddingRight=(25*#SkinSizeRatio#)
PaddingBottom=(50*#SkinSizeRatio#)