[Variables]
BarWidth=12
BarHeight=(#WORKAREAHEIGHT#/2)
BarGapX=4
BarGapY=0

FFTAttack=350
FFTDecay=350
FFTSize=2048
FreqMin=40
FreqMax=16000
; Audio settings
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel#FFTOptions

MeasureName=MeasureAudioRepeat
MeterName=MeterBarRepeat

PlayerName=CAD
; The interface name for the media player
; http://docs.rainmeter.net/manual-beta/plugins/nowplaying#playerlist

PrimaryFont=Segoe UI
SecondaryFont=Segoe UI Semilight
FontColor=255,255,255

SkinSizeRatio=0.5

Bands=96
Sensitivity=42
ColorIntensity=1.75
ColorTransitionTime=3.5

ColorPlaylist=AlbumArt
; ColorPlaylist=RandomColorPlaylist
; ColorPlaylist=ExampleColorPlaylist

; See ColorPlaylists.inc file for more color options